---
proxmoxs:
  hosts:
    pve1:
    pve2:

k8s-nodes:
  children:
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.16.211
          ansible_user: ubuntu
        worker2:
          ansible_host: 192.168.16.212
          ansible_user: ubuntu
    masters:
      hosts:
        master1:
          ansible_host: 192.168.16.201
          ansible_user: ubuntu
        master2:
          ansible_host: 192.168.16.202
          ansible_user: ubuntu
